base.cfg, templates/circus.ini, templates/contracting_data_bridge.yaml, versions.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/8)
=> add op.contracting.api

base.cfg, production.cfg, templates/circus.ini, templates/competitive_dialogue_data_bridge.yaml
Підключення мосту для конкурентного діалогу 
Залежить від PR
https://github.com/openprocurement/openprocurement.tender.competitivedialogue/pull/7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/10)
=> Add bridge for competitive dialogue

base.cfg, templates/competitive_dialogue_data_bridge.yaml
Done https://github.com/openprocurement/openprocurement.tender.competitivedialogue/issues/90
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/14)
=> Add public_tenders_api_server in template and base.cfg

bridges_base.cfg, versions.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/16)
=> Add redis flush script and redis config 

.gitignore, base.cfg
Fix buildout for compability with edge without openprocurement dependencies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/19)
=> Delete openprocurement dependencies

base.cfg, templates/couchdb.ini, templates/edge_data_bridge.yaml, templates/edge_data_bridge_auctions.yaml, templates/edge_data_bridge_contracts.yaml, templates/edge_data_bridge_plans.yaml, templates/edge_data_bridge_tenders.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/20)
=> Add configurable variables for batch mode

buildout.cfg, templates/openprocurement.api.ini, versions.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/27)
=> Fix for op.api Couch UUID validation by NewRequest subscriber

aws_startup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/28)
=> Formating couchdb url in etc/openprocurement.api.ini

base.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/30)
=> Added openprocurement.historical

profiles/versions.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/31)
=> Update pinned versions of packages

base.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/33)
=> A304530935131375 archivarius integration

.gitignore, buildout.cfg.example, profiles/archivarius.cfg, profiles/base.cfg, templates/edge_data_bridge.yaml, templates/openprocurement.edge.ini
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/36)
=> Buildout Fixes

buildout.cfg.example
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/38)
=> Fix buildout.cfg.example

profiles/base.cfg, profiles/sources.cfg, templates/openprocurement.api.ini
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/40)
=> A324451936699894 archivarius on refactoring

buildout.cfg, penstock_statsd.cfg, statsd.cfg, templates/api_handler.yaml, templates/openprocurement.api.ini, templates/penstock.yaml, templates/penstock_handler.yaml, versions.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/45)
=> Scale 2 0 to monitoring

profiles/contracts.cfg, profiles/plans.cfg, profiles/tenders.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/52)
=> Add config files

profiles/production.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/55)
=> Up edge version

bootstrap.sh, profiles/base.cfg, requirements.txt, templates/logrotate.conf
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/57)
=> Added s3cmd for logrotate and buildout isolation 

profiles/base.cfg, profiles/sources.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/60)
=> Add Historical

profiles/base.cfg, profiles/sources.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/61)
=> Add frameworkagreement

buildout.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/62)
=> update index at buildout.cfg section

profiles/production.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/64)
=> Production

base.cfg, development.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/65)
=> replace source for development

profiles/base.cfg, templates/circus.ini
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/69)
=> Added timestamp adding to stderr and stdout records of circus

templates/couchdb.ini
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/73)
=> Remove default compaction rule

base.cfg, versions.cfg
* Update source for openprocurement.api
* Update cornice, pyramid and WebOb versions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/74)
=> A565404995871133 refactoring api

base.cfg, versions.cfg
* Remove version of openprocurement_client from versions.cfg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/78)
=> Add missing remotes variables in base.cfg

profiles/templates.cfg, templates/plugins.yaml
Change openprocurement.api.ini template due to new plugins
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/80)
=> A579936517956533 tricky pmt

profiles/development.cfg, profiles/sources.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/82)
=> Add swiftsure package to sources

profiles/base.cfg, profiles/sources.cfg, profiles/templates.cfg, profiles/versions.cfg, templates/circus.ini, templates/contracting_data_bridge.yaml, templates/redis.conf
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/84)
=> Add contracting module

profiles/production.cfg, profiles/versions.cfg, templates/couchdb.ini
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/86)
=> Production migration a674795074275495

profiles/versions.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/87)
=> Remove duplication

profiles/sources.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/88)
=> A674862507884909 update sources

profiles/base.cfg, profiles/sources.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/89)
=> Add openprocurement.contracting.ceasefire

profiles/base.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/96)
=> Comment out contracting common

README.md, buildout.cfg, buildout.cfg.example, requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/97)
=> A721150900813442 dev environment

buildout.cfg, profiles/versions.cfg, pytest.ini
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/100)
=> add pytest support

profiles/base.cfg, profiles/sources.cfg, profiles/versions.cfg
Also use it's entrypoint to add script to the bin folder
of buildout.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/101)
=> Add caravan

profiles/base.cfg, profiles/sources.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/103)
=> Add appraisal auction

profiles/development.cfg, profiles/sources.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.buildout/107)
=> Add lots.bargain
